ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "isLifetimePlus" BOOLEAN NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS "PlusGift" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "giftedBy" TEXT NOT NULL,
  "giftType" TEXT NOT NULL,
  "note" TEXT,
  "revokedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PlusGift_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "PlusGift_userId_idx" ON "PlusGift"("userId");

ALTER TABLE "PlusGift" ADD CONSTRAINT "PlusGift_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
